services:
  nginx.gateway:
    build:
      dockerfile: Dockerfile
      context: ./services/nginx
    volumes:
      - ./frontend/dist:/var/www/html
      - ./services/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api.upload
      - api.stream
      - api.auth
      - frontend.public
    ports:
      - '80:80'
    networks:
      - vibe_stream_net

  frontend.public:
    container_name: frontend.public
    build:
      dockerfile: Dockerfile
      context: frontend/public
    volumes:
      - ./frontend/public/src:/frontend/public/app
      - /frontend/public/app/node_modules
    ports:
      - '5173:5173'
    restart: always
    networks:
      - vibe_stream_net

  api.auth:
    container_name: api.auth
    build:
      dockerfile: Dockerfile
      context: ./backend/auth
    volumes:
      - ./backend/auth/src:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - '3000:3000'
    networks:
      - vibe_stream_net

  api.main:
    container_name: api.main
    build:
      dockerfile: Dockerfile
      context: backend/java/api-main
    depends_on:
      - db.postgresql.main
      - storage.minio
      - rabbit.mq
    ports:
      - "8080:8080"
    networks:
      - vibe_stream_net

  api.upload:
    container_name: api.upload
    build:
      dockerfile: Dockerfile
      context: backend/java/api-upload
    depends_on:
      - db.postgresql.main
      - storage.minio
      - rabbit.mq
    ports:
      - "8081:8081"
    networks:
      - vibe_stream_net

  api.stream:
    container_name: api.stream
    build:
      dockerfile: Dockerfile
      context: ./backend/java/api-stream
    depends_on:
      - storage.minio
    ports:
      - "8082:8082"
    networks:
      - vibe_stream_net

  image.handler:
    container_name: image.handler
    build:
      dockerfile: Dockerfile
      context: ./backend/java/image-handler
    depends_on:
      - storage.minio
      - rabbit.mq
    networks:
      - vibe_stream_net

  external.api.handler:
    container_name: external.api.handler
    build:
      dockerfile: Dockerfile
      context: ./backend/java/external-api-handler
    depends_on:
      - storage.minio
      - rabbit.mq
    networks:
      - vibe_stream_net

  audio.handler:
    container_name: audio.handler
    build:
      dockerfile: Dockerfile
      context: ./backend/java/audio-handler
    depends_on:
      - storage.minio
      - rabbit.mq
    networks:
      - vibe_stream_net

  websocket.server.1:
    container_name: websocket.server.1
    build:
      dockerfile: Dockerfile
      context: ./backend/websocket
    volumes:
      - ./backend/websocket/src:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - '3001:3001'
    networks:
      - vibe_stream_net

  db.redis:
    container_name: db.redis
    build:
      dockerfile: Dockerfile
      context: ./services/redis
    volumes:
      - ./volumes/db/redis:/data
    ports:
      - "6379:6379"
    networks:
      - vibe_stream_net

  db.mysql.users:
    container_name: db.mysql.users
    build:
      dockerfile: Dockerfile
      context: ./services/mysql
    volumes:
      - ./volumes/db/mysql/users:/var/lib/mysql
    env_file:
      - .env
    ports:
      - '3306:3306'
    networks:
      - vibe_stream_net

  db.postgresql.main:
    container_name: db.postgresql.main
    build:
      dockerfile: Dockerfile
      context: ./services/postgresql
    volumes:
      - ./volumes/db/postgresql/main:/var/lib/postgresql
    env_file:
      - .env
    ports:
      - '5432:5432'
    restart: always
    networks:
      - vibe_stream_net

  storage.minio:
    container_name: storage.minio
    build:
      dockerfile: Dockerfile
      context: ./services/minio
    volumes:
      - ./volumes/storage/minio/vibestream:/var/lib/minio
    env_file:
      - .env
    ports:
      - "9000:9000"
      - "9001:9001"
    networks:
      - vibe_stream_net

  rabbit.mq:
    container_name: rabbit.mq
    build:
      dockerfile: Dockerfile
      context: ./services/rabbitmq
    env_file:
      - .env
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - vibe_stream_net

  phpmyadmin:
    image: phpmyadmin
    environment:
      - PMA_HOST=db.mysql.users
      - PMA_PORT=3306
    ports:
      - 9090:80
    networks:
      - vibe_stream_net

networks:
  vibe_stream_net:
    driver: bridge