services:
  auth.api:
    container_name: auth.api
    build:
      dockerfile: Dockerfile
      context: ./backend/auth
    volumes:
      - ./backend/auth/src:/usr/src/app
    ports:
      - '3000:3000'
    networks:
      - vibecloud_net

  laravel.api:
    container_name: laravel.api
    build:
      dockerfile: Dockerfile_api
      context: backend/php/
    volumes:
      - ./backend/php/src:/app
    depends_on:
      - db.mysql
    ports:
      - '8000:8000'
    networks:
      - vibecloud_net

  java.api:
    container_name: java.api
    build:
      dockerfile: Dockerfile
      context: ./backend/java/api
    depends_on:
      - db.mysql
      - storage.minio
      - rabbit.mq
    ports:
      - "8080:8080"
    networks:
      - vibecloud_net

  java.image.handler:
    container_name: java.image.handler
    build:
      dockerfile: Dockerfile
      context: ./backend/java/image-handler
    depends_on:
      - storage.minio
      - rabbit.mq
    networks:
      - vibecloud_net

  nginx.router:
    build:
      dockerfile: Dockerfile
      context: ./services/nginx
    volumes:
      - ./frontend:/var/www/html
      - ./services/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - laravel.api
      - java.api
      - auth.api
      - frontend.public
    ports:
      - '80:80'
    networks:
      - vibecloud_net


  db.redis:
    container_name: db.redis
    build:
      dockerfile: Dockerfile
      context: ./services/redis
    volumes:
      - ./volumes/db/redis/jobs:/data
    ports:
      - "6379:6379"
    networks:
      - vibecloud_net

  db.mysql:
    container_name: db.mysql
    build:
      dockerfile: Dockerfile
      context: ./services/mysql
    volumes:
      - ./volumes/db/mysql/main:/var/lib/mysql
    env_file:
      - .env
    ports:
      - '3306:3306'
    networks:
      - vibecloud_net

  storage.minio:
    container_name: storage.minio
    build:
      dockerfile: Dockerfile
      context: ./services/minio
    volumes:
      - ./volumes/storage/minio/vibecloud:/var/lib/minio
    env_file:
      - .env
    ports:
      - "9000:9000"
      - "9001:9001"
    networks:
      - vibecloud_net

  rabbit.mq:
    container_name: rabbit.mq
    build:
      dockerfile: Dockerfile
      context: ./services/rabbitmq
    env_file:
      - .env
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - vibecloud_net

  phpmyadmin:
    image: phpmyadmin
    environment:
      - PMA_HOST=db.mysql
      - PMA_PORT=3306
    ports:
      - 9090:80
    networks:
      - vibecloud_net

networks:
  vibecloud_net:
    driver: bridge